### ISSUE TITLE
возвращать объект

### ISSUE THREAD

**Issue by DIY0R** [HowProgrammingWorks/API#3]
https://github.com/HowProgrammingWorks/API/blob/57e8e4665fa866197b68464561d851bbdf20b870/JavaScript/1-HTTP/api/move.js#L17

Я  думаю лучшее возвращать объект содержащий информаций о том что был ли успешно добавлен в базу или нет ....

**Comment by tshemsedinov** [comment]
Тут можно улучшать долго
- передавать коды http ошибок вместо строк
- для ошибок сделать кастомные классы, сериализировать их и восстанавливать на клиенте в виде экземпляров
- добавить тайпинги или схемы, делать валидацию
Но все это не важно доля демонстрации идеи. А продакшен-реди код тут: https://github.com/metarhia/Example
